[package]
name = "imgcmp"
version = "0.1.0"
authors = ["George Boulougaris <gboulougaris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgcmp-lib = { path = "../lib" }
anyhow = "1.0.32"
image = "0.23.12"
